### ISSUE TITLE
Storybook: Candidate Card Component 

### ISSUE THREAD

**Issue by shanhaider23** [HackYourFuture-CPH/simply-name.it#18]
### User story
**Who**: As a developer

**What**: I want a Candidate Card component and List of Cards that allows displaying each candidate and List.  

**Why**: so the user can easily vote for their choice 

### Acceptance criteria
Create a storybook component like the one highlighted in the image:
![Skærmbillede 2021-07-05 224733](https://user-images.githubusercontent.com/75579156/124517967-9b702780-dde5-11eb-86bf-7d3cf1d46631.png)
**List of Cards**
![image (3)](https://user-images.githubusercontent.com/75579156/124558863-5676e000-de3b-11eb-962c-4cc80ac5f6d2.png)

**Comment by dpfernandes** [comment]
done
